 module.exports = {
    PORT: 5000,
    MOVIEDB_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4ZjZjMThjZWMzYmRjMzY5YzMxNWRiODVlM2I5YjljNyIsInN1YiI6IjViNmFhYTgwMGUwYTI2N2VmODExNjM4OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.DZlW5JH5V-tudfL9qFVyZT_8vQP4MghhgsbqLEEmEjg",
 }; 